spring.application.name=emsi-bot
spring.ai.google.genai.api-key=${CHATBOT_GEMINI_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
server.port=8087
spring.ai.mcp.client.streamable-http.connections.mcprh.url=http://localhost:8989/mcp
telegram.api.key=${TELEGRAM_API_KEY}
telegram.bot.name=${TELEGRAM_BOT_NAME:FetheddineAIBot}